# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: https-jackhsu1002-github-io-blog
google_analytics: UA-138378036-1
title: JackHsu

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Blog J

description: Attitude is everything
author:
  name: JackHsu
  email: bedrose0921@gmail.com.com
  github: JackHsu1002
  twitter: JackHsu03328995
  pinterest: bedrose0921
  linkedin: jack-hsu-9560a6165
  bio: Attitude is everything
  email_md5: d9dfa63175bff44a1e5c5eaef686f26d

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
archive_path: archive.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: /Blog
#BASE_PATH: 
baseurl: /Blog

plugins:
  - jekyll-paginate
